version: '3.8'
services:
  php:
    container_name: PHP_SERVER
    restart: always
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www/html

volumes:
  src: {}